DROP TABLE IF EXISTS groups, students, courses, course_enrollment;

CREATE TABLE groups
(
    group_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(5) NOT NULL
);

CREATE TABLE students
(
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   INT REFERENCES groups (group_id),
    first_name VARCHAR(20) NOT NULL,
    last_name  VARCHAR(20) NOT NULL
);

CREATE TABLE courses
(
    course_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name        VARCHAR(20)  NOT NULL,
    course_description VARCHAR(100) NOT NULL
);

CREATE TABLE course_enrollment
(
    student_id INT NOT NULL,
    course_id  INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES students (student_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses (course_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    UNIQUE (student_id, course_id)
);
